### PR TITLE
Make Homey.api callable

### PR DESCRIPTION
**Pull request by OlivierZal**
@jeroenwienk, @WeeJeWel, to address https://github.com/athombv/homey-apps-sdk-issues/issues/282

Tested, works.

### CODE REVIEW

**Comment by jeroenwienk** [comment]
> @jeroenwienk, @WeeJeWel, to address [athombv/homey-apps-sdk-issues#282](https://github.com/athombv/homey-apps-sdk-issues/issues/282)
> 
> Tested, works.

What is this supposed to support can you give an example or reference to docs?

**Comment by OlivierZal** [comment]
@jeroenwienk, it's UI-related, e.g. https://github.com/OlivierZal/com.melcloud.extension/blob/ce0a289274393c15c00ab07aebc0c88bb7464fe2/settings/index.ts#L29

Homey documentation: https://apps.developer.homey.app/advanced/custom-views/app-settings#homey.api-string-method-string-path-mixed-body-function-callback

See https://github.com/athombv/node-homey-apps-sdk-v3-types/pull/27 about the mix between UI and non-UI method signatures in Homey type.

**Comment by jeroenwienk** [comment]
> @jeroenwienk, it's UI-related, e.g. https://github.com/OlivierZal/com.melcloud.extension/blob/ce0a289274393c15c00ab07aebc0c88bb7464fe2/settings/index.ts#L29
> 
> Homey documentation: https://apps.developer.homey.app/advanced/custom-views/app-settings#homey.api-string-method-string-path-mixed-body-function-callback
> 
> See #27 about the mix between UI and non-UI method signatures in Homey type.

Oke I understand now but those are front-end types and basically have nothing to do with the sdk types. As is the Homey instance in the front end is not the same as this.homey in apps.

**Comment by OlivierZal** [comment]
Is handled by https://github.com/athombv/node-homey-apps-sdk-v3-types/pull/27

**Pull request closed without merging**
